name: CI

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request: {}

env:
  CI: 'true'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
        with:
          node-version: 18.x
          yarn-version: 1.x
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Lint JS
        run: yarn lint:js
      - name: Test
        run: yarn test

  try-scenarios:
    name: ${{ matrix.ember-try-scenario }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
        with:
          node-version: 18.x
          yarn-version: 1.x
      - name: Install dependencies
        run: yarn install
      - name: Test
        env:
          EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
        run: yarn ember try:one $EMBER_TRY_SCENARIO

        working-directory: packages/test-app
